INSERT INTO peces (nombre_cientifico,nombre_comun,taxonomia,origen,descripcion,biologia_ecologia,distribucion) VALUES ('*Barbus graellsii*','Barbo de Graells','Clase: Actinopterygii, Orden: Cypriniformes, Familia: Cyprinidae','Autóctona','Especie de gran tamaño, que puede alcanzar tallas máximas de hasta 80 cm de longitud total, aunque la mayoría no suele superar los 35 cm. El cuerpo es más alargado y esbelto que el de las especies que le son más próximas, es decir: B. bocagei, B. guiraonis y B. sclateri. La aleta dorsal en los ejemplares adultos no presenta denticulaciones en el último radio sencillo, mientras que pueden aparecer de forma excepcional en los ejemplares más jóvenes.
La aleta dorsal se encuentra en la misma vertical que las demás.
Los labios en general son gruesos, presentando el inferior un lóbulo medio bien desarrollado.

Los machos son más pequeños que las hembras y, en época de reproducción, muestran tubérculos nupciales muy desarrollados en la región anterior de la cabeza. El color del cuerpo es pardo verdoso y moteado en juveniles. En el delta del Ebro, los machos viven entre 11 y 12 años, es decir, menos que las hembras que suelen vivir hasta los 16 años; edades que corresponden respectivamente a intervalos de talla de 38-40 cm para machos y 42-46 cm para hembras.','Existe una tendencia marcadamente regresiva en las poblaciones, aunque todavía es localmente abundante en algunos ríos.
Barbus graellsii es una especie que puede colonizar todo tipo de medios, aunque prefiere los cursos medios y bajos de los ríos. En los tramos altos de su área de distribución esta especie es sustituida por B. haasi y B. meridionalis. Se la encuentra en los tramos altos únicamente en la época de reproducción, buscando zonas de arena y grava donde realizar la puesta, siendo esta una especie litófila. Como ocurre en otras especies del género Barbus, prefiere zonas tranquilas con vegetación y raíces de árboles y cuevas donde encuentra refugios. Tienen hábitos gregarios, para lo que suelen formar agrupaciones, incluso con otras especies de ciprínidos, como Squalius cephalus y Chondrostoma toxostoma. Presentan una alimentación variada, según la disponibilidad de recursos del medio, pero en general se alimentan tanto de algas como de macroinvertebrados acuáticos.

Machos y hembras alcanzan la madurez sexual a los 4 años (algunos machos lo hacen a los 3 años), con tallas corporales de 15 a 20 cm. Cada hembra pone de 5.000 a 25.000 huevos. La época de reproducción dura desde mayo hasta agosto, siendo máximo el número de óvulos maduros en junio.','España: se distribuye básicamente en la cuenca del Ebro, aunque también se encuentra en otros
ríos del norte de España. En el cantábrico hasta el río Asón y en Cataluña hasta el río Ter.
DE: especie endémica de España.
Mundo: especie endémica de España.')